"""D-1641 EC and chloride regulatory standards for dms_datastore_ui catalog.

Generates time series of D-1641 regulatory standards (State Water Resources
Control Board Decision 1641) for key Delta compliance stations. Standards are
driven by Sacramento Valley water year types read from a historical WSIHIST text
file (http://cdec.water.ca.gov/reportapp/javareports?name=WSIHIST).

Stations covered
----------------
emm  Emmaton (USBR, CDEC D22A) — corresponds to DSM2 RSAC092
jer  Jersey Point (USBR, CDEC D15) — corresponds to DSM2 RSAN018
rsl  Rock Slough at Contra Costa Canal — corresponds to DSM2 ROLD024

Standards generated
-------------------
D1641_AG_WI    14-day running avg EC, Agricultural W&I Delta (microS/cm)
D1641_FWS_SJR  14-day running avg EC, Fish & Wildlife Service SJR (microS/cm)
D1641_MI_250   Daily chloride, Municipal & Industrial intake (mg/L)

The Rock Slough MI 250 Cl standard (250 mg/L constant) can be displayed on a
dual Y-axis alongside observed EC via the multi_y behaviour enabled in
DatastoreUIMgr.get_convertible_unit_groups. The rsl_ec_to_cl regression bundled
here can be used separately to derive observed chloride from observed EC.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Tuple

import numpy as np
import pandas as pd
from shapely.geometry import Point

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Station and standard metadata
# ---------------------------------------------------------------------------


class D1641StandardSpec(NamedTuple):
    """Specification for one D-1641 regulatory standard set."""

    name: str             # Catalog param name, e.g. "D1641_AG_WI"
    csv_filename: str     # Filename in the bundled data/d1641/ directory
    unit_scale: float     # Multiply CSV values by this (1000 for mmhos→microS/cm)
    unit: str             # Output unit string, e.g. "microS/cm" or "mg/L"
    dsm2_locations: List[str]  # DSM2 station IDs in the CSV to process


#: Standard sets generated by default.
DEFAULT_STANDARDS: List[D1641StandardSpec] = [
    # ── Agricultural – Western & Interior Delta ─────────────────────────────
    # 14-day running average of daily mean EC (mmhos/cm → microS/cm × 1000).
    # D-1641 Table 2-1:  Emmaton (D-22), Jersey Point (D-15), Terminous (C-13),
    # San Andreas Landing (C-4), Prisoners Point (D-29).
    D1641StandardSpec(
        name="D1641_AG_WI",
        csv_filename="D1641_AG_wiDelta.csv",
        unit_scale=1000.0,
        unit="microS/cm",
        dsm2_locations=["RSAC092", "RSAN018"],
    ),
    # ── Fish & Wildlife Service – San Joaquin River ─────────────────────────
    # 14-day running average of daily mean EC; Jersey Point only for the
    # stations present in dms_datastore.  D-1641 Table 2-2.
    D1641StandardSpec(
        name="D1641_FWS_SJR",
        csv_filename="D1641_FWS_SJR.csv",
        unit_scale=1000.0,
        unit="microS/cm",
        dsm2_locations=["RSAN018"],
    ),
    # ── Agricultural – South Delta ──────────────────────────────────────────
    # 30-day running average of daily mean EC (D-1641 Table 2-1):
    # 0.7 mmhos/cm (700 microS/cm) Apr 30–Sep 1; 1.0 mmhos/cm otherwise.
    # Note: OLD_MID (C-8, Old River near Middle River) is a model aggregate
    # point with no single matching observed station; omitted here.
    D1641StandardSpec(
        name="D1641_AG_S_DELTA",
        csv_filename="D1641_AG_sDelta.csv",
        unit_scale=1000.0,
        unit="microS/cm",
        dsm2_locations=["RSAN112", "RSAN072", "ROLD059"],
    ),
    # ── Agricultural – Export (Banks & Tracy) ───────────────────────────────
    # Monthly average of daily mean EC ≤ 1.0 mmhos/cm (1000 microS/cm)
    # year-round.  D-1641 Table 2-1 export objectives.
    D1641StandardSpec(
        name="D1641_AG_EXPORT",
        csv_filename="D1641_AG_export.csv",
        unit_scale=1000.0,
        unit="microS/cm",
        dsm2_locations=["CHDMC006", "CHSWP003"],
    ),
    # ── Fish & Wildlife Service – Suisun Marsh ──────────────────────────────
    # Monthly mean of daily-maximum EC (or average of 2 high tides).
    # D-1641 Table 2-2 Suisun Marsh objectives.  Values are WYT-independent
    # (same for W/AN/BN/D/C) and seasonal: 8–19 mmhos/cm Oct–May, 0 (NaN)
    # Jun–Sep (no standard in summer). Stations: Collinsville (C-2),
    # National Steel (S-64), Beldons Landing (S-49).
    # NOTE: D-1641 also specifies conditional low-flow tightening for Suisun
    # that requires the Sacramento River Index; that logic is not applied here.
    D1641StandardSpec(
        name="D1641_FWS_SUISUN",
        csv_filename="D1641_FWS_Suisun.csv",
        unit_scale=1000.0,
        unit="microS/cm",
        dsm2_locations=["RSAC081", "SLMZU025", "SLMZU011"],
    ),
    # ── Municipal & Industrial – 250 mg/L Chloride ──────────────────────────
    # Daily chloride ≤ 250 mg/L, all water year types.  D-1641 Table 2-3.
    # Stations: Rock Slough/CCC (C-5), Banks/Clifton Court (C-9),
    # Tracy/DMC (DMC-1), Barker Slough (C-16), Cache Slough at Vallejo (C-19).
    D1641StandardSpec(
        name="D1641_MI_250",
        csv_filename="D1641_MI_250.csv",
        unit_scale=1.0,
        unit="mg/L",
        dsm2_locations=["ROLD024", "CHSWP003", "CHDMC006", "SLBAR002", "SLCCH016"],
    ),
    # ── Municipal & Industrial – 150 mg/L Chloride (stricter, Rock Slough) ──
    # Seasonal WYT-dependent chloride standard for Rock Slough only, applied
    # from January 1 onward.  Values (mg/L): W=240, AN=190, BN=175, D=165,
    # C=155.  More stringent than the year-round 250 mg/L standard.
    D1641StandardSpec(
        name="D1641_MI_150",
        csv_filename="D1641_MI_150.csv",
        unit_scale=1.0,
        unit="mg/L",
        dsm2_locations=["ROLD024"],
    ),
]

#: Mapping from DSM2 model station ID to dms_datastore observed station_id.
#: Sources: dms_datastore/config_data/station_dbase.csv (CDEC codes in comments).
DSM2_TO_DATASTORE_ID: Dict[str, str] = {
    # ── AG W&I Delta / FWS SJR ──────────────────────────────────────────────
    "RSAC092": "emm",    # Sacramento at Emmaton (USBR, CDEC D22A — D-1641 D-22)
    "RSAN018": "jer",    # SJR at Jersey Point (USBR, CDEC D15 — D-1641 D-15)
    # ── AG South Delta ──────────────────────────────────────────────────────
    "RSAN112": "ver",    # SJR at Vernalis (USBR, CDEC C10 — D-1641 C-10)
    "RSAN072": "bdt",    # SJR at Brandt Bridge (NCRO B95740 — D-1641 C-6)
    "ROLD059": "old",    # Old River at Tracy Blvd (NCRO B95380 — D-1641 P-12)
    # ── AG Export ───────────────────────────────────────────────────────────
    "CHDMC006": "trp",   # Tracy/Delta-Mendota Canal PP (USBR — D-1641 DMC-1)
    "CHSWP003": "hbp",   # Harvey O. Banks PP (DWR — D-1641 C-9)
    # ── FWS Suisun Marsh ────────────────────────────────────────────────────
    "RSAC081": "cse",    # Sacramento at Collinsville (DES, CDEC C2B — D-1641 C-2)
    "SLMZU025": "nsl",   # Montezuma Sl. at National Steel (NCRO E33670, CDEC S64)
    "SLMZU011": "bdl",   # Montezuma Sl. near Beldons Landing (DES, CDEC S49)
    # ── MI Chloride ─────────────────────────────────────────────────────────
    "ROLD024": "rsl",    # Rock Slough at CCC (DWR B95218 — D-1641 C-5)
    "SLBAR002": "bks",   # Barker Slough PP (DWR — D-1641 C-16/SLSAR3)
    "SLCCH016": "ccs",   # Cache Slough / Old Vallejo PP (USBR — D-1641 C-19)
}

#: UTM Zone 10N (EPSG:26910) (x, y) coordinates keyed by dms_datastore station_id.
#: Sourced from dms_datastore/config_data/station_dbase.csv.
STATION_COORDS: Dict[str, Tuple[float, float]] = {
    # AG W&I Delta / FWS SJR
    "emm": (610598.8, 4215917.6),
    "jer": (615024.3, 4212414.2),
    # AG South Delta
    "ver": (653005.8, 4171637.9),
    "bdt": (647500.8, 4192114.6),
    "old": (636491.6, 4185281.5),
    # AG Export
    "trp": (626865.0, 4186450.0),
    "hbp": (623690.4, 4187532.5),
    # FWS Suisun Marsh
    "cse": (600859.1, 4214643.6),
    "nsl": (597451.6, 4219938.0),
    "bdl": (590134.7, 4227040.1),
    # MI Chloride
    "rsl": (619885.2, 4204031.0),
    "bks": (605228.0, 4237166.9),
    "ccs": (609500.3, 4239525.4),
}

#: Human-readable station names for catalog display.
STATION_NAMES: Dict[str, str] = {
    "emm": "Emmaton",
    "jer": "Jersey Point",
    "ver": "SJR at Vernalis",
    "bdt": "SJR at Brandt Bridge",
    "old": "Old River at Tracy Blvd (P-12)",
    "trp": "Tracy / Delta-Mendota Canal PP",
    "hbp": "Harvey O. Banks Pumping Plant",
    "cse": "Sacramento River at Collinsville",
    "nsl": "Montezuma Slough at National Steel",
    "bdl": "Montezuma Slough near Beldons Landing",
    "rsl": "Rock Slough at Contra Costa Canal",
    "bks": "Barker Slough Pumping Plant",
    "ccs": "Cache Slough at Vallejo",
}


# ---------------------------------------------------------------------------
# Bundled data directory helper
# ---------------------------------------------------------------------------


def _data_dir() -> Path:
    """Return the path to the bundled ``data/d1641/`` directory."""
    try:
        # Python 3.9+ importlib.resources
        from importlib.resources import files
        return Path(str(files("dms_datastore_ui").joinpath("data", "d1641")))
    except (AttributeError, TypeError):
        # Python < 3.9 fallback via __file__
        return Path(os.path.dirname(__file__)) / "data" / "d1641"


def get_default_wyt_file() -> str:
    """Return the path to the bundled WSIHIST water year type file.

    The file is ``dms_datastore_ui/data/wsihist.txt`` — a plain-text snapshot
    of the CDEC WSIHIST report downloaded at package build time and covering
    water years 1906–2025.  It is suitable for passing directly to
    :func:`build_d1641_references` or :func:`read_hist_wateryear_types`.

    Returns
    -------
    str
        Absolute path to the bundled ``wsihist.txt``.
    """
    try:
        from importlib.resources import files
        return str(files("dms_datastore_ui").joinpath("data", "wsihist.txt"))
    except (AttributeError, TypeError):
        return str(Path(os.path.dirname(__file__)) / "data" / "wsihist.txt")


# ---------------------------------------------------------------------------
# Rock Slough EC → Chloride regression  (bundled for future use)
# ---------------------------------------------------------------------------


def rsl_ec_to_cl(ec):
    """Convert Rock Slough EC (µS/cm) to chloride (mg/L) via a piecewise regression.

    The regression is::

        Cl = max(EC × 0.15 − 12.0,  EC × 0.285 − 50)

    Source: ``dsm2_calsim_analysis.nbplot.calsim_dsm2_analysis.rsl_ec_to_cl``

    This function is **not** used in D-1641 standard generation; it is provided
    here so callers can derive observed chloride from observed EC at Rock Slough
    as a math/derived catalog reference.

    Parameters
    ----------
    ec : float, array-like, or pandas.Series
        Electrical conductivity in µS/cm.

    Returns
    -------
    float, numpy.ndarray, or pandas.Series
        Chloride in mg/L.
    """
    if isinstance(ec, pd.Series):
        return ec.apply(lambda x: max(x * 0.15 - 12.0, x * 0.285 - 50))
    ec_arr = np.asarray(ec, dtype=float)
    return np.maximum(ec_arr * 0.15 - 12.0, ec_arr * 0.285 - 50)


# ---------------------------------------------------------------------------
# Current water year type from CDEC WSI (live fetch + monthly cache)
# ---------------------------------------------------------------------------

#: Sacramento Valley Water Year Index thresholds (MAF) per D-1641.
_SVI_THRESHOLDS = [
    ("W",  9.2),   # Wet:          index >= 9.2
    ("AN", 7.8),   # Above Normal: index >  7.8
    ("BN", 6.5),   # Below Normal: index >  6.5
    ("D",  5.4),   # Dry:          index >  5.4
]                  # Critical:     index <= 5.4


def _classify_svi(index_maf: float) -> str:
    """Classify a Sacramento Valley index value (MAF) into a WYT code.

    D-1641 thresholds (index in million acre-feet):
        W  \u2265 9.2
        AN > 7.8, < 9.2   (strictly greater than 7.8)
        BN > 6.5, \u2264 7.8  (strictly greater than 6.5)
        D  > 5.4, \u2264 6.5  (strictly greater than 5.4)
        C  \u2264 5.4
    """
    if index_maf >= 9.2:  return "W"
    if index_maf >  7.8:  return "AN"
    if index_maf >  6.5:  return "BN"
    if index_maf >  5.4:  return "D"
    return "C"


def _no_wsi_result(wy: int) -> dict:
    """Return a 'no forecast data' placeholder dict."""
    return {
        "wy": wy,
        "wyt": None,
        "svi_50pct": None,
        "forecast_date": None,
        "is_final": False,
        "source": "none",
    }


def _parse_wsi_text(text: str, expected_wy: int) -> dict:
    """Parse a plain-text CDEC WSI report and return the current WYT.

    Extracts the Sacramento Valley SVI at 50 % exceedance from the most
    recent forecast row in the report.

    Parameters
    ----------
    text : str
        Plain text extracted from the CDEC WSI ``<pre>`` block.
    expected_wy : int
        The water year number we expect (used as fallback in the result).

    Returns
    -------
    dict
        Keys: ``wy``, ``wyt``, ``svi_50pct``, ``forecast_date``,
        ``is_final``, ``source``.
    """
    import re

    # Header line: "2026 Water Year Forecast as of May 1, 2026"
    header_m = re.search(
        r'(\d{4})\s+Water Year Forecast as of\s+'
        r'((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w*)'
        r'\s+(\d+),\s*(\d{4})',
        text,
    )
    if not header_m:
        logger.warning("WSI parse: 'Water Year Forecast as of' header not found")
        return _no_wsi_result(expected_wy)

    wy = int(header_m.group(1))
    f_month = header_m.group(2)[:3]
    f_day   = int(header_m.group(3))
    f_year  = int(header_m.group(4))
    try:
        forecast_date = pd.Timestamp(f"{f_year}-{f_month}-{f_day}")
    except Exception:
        return _no_wsi_result(expected_wy)

    # Locate the Sacramento Valley SVI section
    svi_start = text.find("SACRAMENTO VALLEY WATER YEAR TYPE INDEX")
    if svi_start == -1:
        logger.warning("WSI parse: Sacramento Valley SVI section not found")
        return _no_wsi_result(expected_wy)

    svi_text = text[svi_start:]
    notes_start = svi_text.find("Index =")
    if notes_start > 0:
        svi_text = svi_text[:notes_start]

    # Match forecast rows — use [ \t]+ (not \s+) to stay within one line.
    # The 25 % and 10 % columns wrap to the next line in the WSI report, but
    # the first four columns (99 %, 90 %, 75 %, 50 %) are on the date line.
    rows = re.findall(
        r'((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)'
        r'\s+\d+,\s*\d{4})'
        r'[ \t]+([\d.]+)[ \t]+([\d.]+)[ \t]+([\d.]+)[ \t]+([\d.]+)',
        svi_text,
    )
    if not rows:
        logger.warning("WSI parse: no SVI forecast rows found")
        return _no_wsi_result(expected_wy)

    # Last row = most recent forecast; tuple = (date, 99%, 90%, 75%, 50%)
    try:
        svi_50 = float(rows[-1][4])
    except (IndexError, ValueError):
        return _no_wsi_result(expected_wy)

    wyt = _classify_svi(svi_50)
    is_final = forecast_date.month >= 5   # May 1 or later is the final D-1641 type

    logger.debug(
        "WSI WY %d: %s, SVI 50%%=%.2f → %s (final=%s)",
        wy, forecast_date.date(), svi_50, wyt, is_final,
    )
    return {
        "wy": wy,
        "wyt": wyt,
        "svi_50pct": svi_50,
        "forecast_date": forecast_date,
        "is_final": is_final,
        "source": "wsi_live",
    }


def _fetch_wsi_live(expected_wy: int) -> dict:
    """Fetch and parse the live CDEC WSI page."""
    try:
        import urllib.request
        from bs4 import BeautifulSoup

        url = "http://cdec.water.ca.gov/reportapp/javareports?name=WSI"
        req = urllib.request.Request(
            url, headers={"User-Agent": "dms_datastore_ui/wyt_fetch"}
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            html = resp.read().decode("utf-8", errors="replace")

        soup = BeautifulSoup(html, "html.parser")
        pre = soup.find("pre")
        text = pre.get_text() if pre else soup.get_text()
    except Exception as exc:
        logger.warning("WSI live fetch failed: %s", exc)
        return _no_wsi_result(expected_wy)

    return _parse_wsi_text(text, expected_wy)


def fetch_current_wyt(cache_dir: str | None = None) -> dict:
    """Return the current water year type from the CDEC WSI, with monthly caching.

    The CDEC Water Supply Index (WSI) is issued on the 1st of each month from
    December through May.  The final D-1641 type is the **May 1 50 % exceedance
    forecast**.  For October and November, no forecast has been issued yet and
    this function returns a ``'none'`` result.

    Caching uses ``diskcache`` (already a dms_datastore_ui dependency).  The
    cache key changes each calendar month so new forecasts are picked up
    automatically; entries also expire after 30 days.

    Parameters
    ----------
    cache_dir : str, optional
        Override the cache directory.  Defaults to
        ``~/.dms_datastore_ui/wsi_cache``.

    Returns
    -------
    dict with keys:
        ``wy`` (int), ``wyt`` (str or None), ``is_final`` (bool),
        ``forecast_date`` (Timestamp or None), ``svi_50pct`` (float or None),
        ``source`` ('wsi_live' | 'wsi_cached' | 'none')
    """
    import diskcache

    today = pd.Timestamp.now()
    # WY n covers Oct(n-1) – Sep(n); e.g. WY 2027 starts Oct 1, 2026
    current_wy = today.year + 1 if today.month >= 10 else today.year

    # Oct and Nov: no WSI forecast issued for this WY yet
    if today.month in (10, 11):
        return _no_wsi_result(current_wy)

    cache_path = cache_dir or str(Path.home() / ".dms_datastore_ui" / "wsi_cache")
    key = f"wsi_wyt_{today.year}_{today.month:02d}"

    cache = None
    try:
        cache = diskcache.Cache(cache_path)
        cached = cache.get(key)
        if cached is not None:
            result = dict(cached)
            result["source"] = "wsi_cached"
            return result
    except Exception as exc:
        logger.warning("WSI cache read failed (%s): %s", cache_path, exc)

    result = _fetch_wsi_live(current_wy)

    if cache is not None:
        try:
            cache.set(key, result, expire=60 * 60 * 24 * 30)  # 30-day TTL
        except Exception as exc:
            logger.warning("WSI cache write failed: %s", exc)

    return result


# ---------------------------------------------------------------------------
# Utility functions  (adapted from dsm2_calsim_analysis.utilities.utilities)
# ---------------------------------------------------------------------------


def read_hist_wateryear_types(fpath: str) -> pd.DataFrame:
    """Read historical Sacramento Valley water year types from a WSIHIST text file.

    The expected source is the fixed-width table from CDEC at
    http://cdec.water.ca.gov/reportapp/javareports?name=WSIHIST — the upper
    table, stopping before the min/average rows at the bottom.

    Parameters
    ----------
    fpath : str or path-like
        Path to the WSIHIST text file.

    Returns
    -------
    pandas.DataFrame
        Columns include ``wy`` (int), ``sac_yrtype`` (str: W/AN/BN/D/C), and
        SJR equivalents.  Suitable for passing directly to
        :func:`build_d1641_references`.
    """
    df = pd.read_fwf(
        fpath,
        header=None,
        names=[
            "wy",
            "sac_oct_mar",
            "sac_apr_jul",
            "sac_wysum",
            "sac_index",
            "sac_yrtype",
            "sjr_oct_mar",
            "sjr_apr_jul",
            "sjr_wysum",
            "sjr_index",
            "sjr_yrtype",
        ],
        skiprows=14,
    )
    return df


def _read_regulations(fpath: str, df_wyt: pd.DataFrame) -> pd.DataFrame:
    """Build an irregular regulation step-function from a D-1641 lookup CSV.

    Parameters
    ----------
    fpath : str or path-like
        D-1641 CSV with columns ``location``, ``wyt``, ``month``, ``date``,
        ``val``; lines starting with ``#`` are comments.
    df_wyt : pandas.DataFrame
        Water year type table with at minimum columns ``wy`` and
        ``sac_yrtype``.

    Returns
    -------
    pandas.DataFrame
        DatetimeIndex, columns ``value`` (float) and ``location`` (str).
        Each row is a step-function breakpoint; the regulation value is
        constant from that timestamp until the next breakpoint for the same
        location.
    """
    df = pd.read_csv(fpath, comment="#")
    df[["month", "date"]] = df[["month", "date"]].astype(int)
    df_wy = df_wyt[df_wyt["sac_yrtype"].notnull()].copy()
    yr_start = int(df_wy["wy"].min())
    yr_end = int(df_wy["wy"].max())
    locs = df["location"].unique()
    dfs = []
    for loc in locs:
        timestamps = []
        regs = []
        for wy in range(yr_start, yr_end + 1):
            wyt_rows = df_wyt[df_wyt["wy"] == wy]["sac_yrtype"]
            if wyt_rows.empty:
                continue
            wyt = wyt_rows.iloc[0]
            mask = (df["wyt"] == wyt) & (df["location"] == loc)
            for _, row in df[mask].iterrows():
                mo = int(row["month"])
                yr_cal = wy - 1 if mo >= 10 else wy
                t_start = pd.Timestamp(
                    f"{yr_cal:d}-{mo:02d}-{int(row['date']):02d}"
                )
                timestamps.append(t_start)
                regs.append(float(row["val"]))
        if timestamps:
            dfs.append(
                pd.DataFrame(
                    {"value": regs, "location": loc},
                    index=pd.DatetimeIndex(timestamps),
                )
            )
    if not dfs:
        return pd.DataFrame(
            columns=["value", "location"],
            index=pd.DatetimeIndex([]),
        )
    return pd.concat(dfs)


def _generate_regulation_timeseries(
    df_reg: pd.DataFrame,
    location: str,
    start_date,
    end_date,
    freq: str = "D",
) -> pd.DataFrame:
    """Expand an irregular regulation step-function to a dense regular series.

    This is a refactored version of ``generate_regulation_timeseries`` from
    ``dsm2_calsim_analysis.utilities``, taking explicit date bounds instead of
    deriving them from an observed-data DataFrame (resolving the upstream FIXME).

    Parameters
    ----------
    df_reg : pandas.DataFrame
        Output of :func:`_read_regulations`.
    location : str
        DSM2 station ID to extract, e.g. ``"RSAC092"``.
    start_date, end_date : date-like
        Inclusive start/end of the output time series.
    freq : str
        Pandas offset alias for the output grid.  Default ``"D"`` (daily).

    Returns
    -------
    pandas.DataFrame
        Index: DatetimeIndex named ``"datetime"``, single column ``"value"``.
    """
    start = pd.Timestamp(start_date)
    end = pd.Timestamp(end_date)

    df_loc = df_reg[df_reg["location"] == location].sort_index()
    # Expand search window so breakpoints just outside start/end are captured.
    window_mask = (
        (df_loc.index >= (start - pd.Timedelta("400 days")))
        & (df_loc.index <= (end + pd.Timedelta("400 days")))
    )
    df_win = df_loc[window_mask]

    times: list = []
    values: list = []
    for i in range(len(df_win) - 1):
        row_i = df_win.iloc[i]
        row_next = df_win.iloc[i + 1]
        segment = pd.date_range(
            start=row_i.name, end=row_next.name, freq=freq, inclusive="left"
        )
        times.extend(segment.tolist())
        values.extend([row_i["value"]] * len(segment))

    # Extend from the last breakpoint to end_date so the series covers the
    # full requested period (the loop above always omits the final row).
    if len(df_win) > 0:
        last_row = df_win.iloc[-1]
        tail_start = last_row.name
        if tail_start <= end:
            tail = pd.date_range(start=tail_start, end=end, freq=freq, inclusive="left")
            if len(tail) > 0:
                # Avoid double-counting if tail_start was already the boundary of
                # the previous segment.
                t0 = pd.Timestamp(times[-1]) + pd.tseries.frequencies.to_offset(freq) if times else tail_start
                tail = tail[tail >= t0]
                times.extend(tail.tolist())
                values.extend([last_row["value"]] * len(tail))

    if not times:
        return pd.DataFrame(
            {"value": pd.Series(dtype=float)},
            index=pd.DatetimeIndex([], name="datetime"),
        )

    df_ts = pd.DataFrame(
        {"value": values},
        index=pd.DatetimeIndex(times, name="datetime"),
    )
    return df_ts.loc[start:end]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_d1641_references(
    wyt_file: str,
    standards: Optional[List[D1641StandardSpec]] = None,
    station_id_map: Optional[Dict[str, str]] = None,
    station_coords: Optional[Dict[str, Tuple[float, float]]] = None,
) -> list:
    """Build DataReference objects for D-1641 regulatory standards.

    Each reference is backed by a
    :class:`~dvue.catalog.CallableDataReferenceReader` and carries metadata
    compatible with the ``DatastoreUIMgr`` catalog schema (``station_id``,
    ``subloc``, ``param``, ``unit``, ``agency``, ``geometry``, ``min_year``,
    ``max_year``).  The references use the same ``station_id`` values as the
    corresponding observed stations, enabling direct side-by-side comparison in
    the UI.

    Parameters
    ----------
    wyt_file : str or path-like
        Path to a WSIHIST-format historical water year type text file from CDEC.
    standards : list of D1641StandardSpec, optional
        Standards to generate.  Defaults to :data:`DEFAULT_STANDARDS`.
    station_id_map : dict, optional
        Override mapping from DSM2 location ID to dms_datastore
        ``station_id``.  Defaults to :data:`DSM2_TO_DATASTORE_ID`.
    station_coords : dict, optional
        Override UTM Zone 10N ``(x, y)`` coords keyed by ``station_id``.
        Defaults to :data:`STATION_COORDS`.

    Returns
    -------
    list of dvue.catalog.DataReference
        One reference per (standard × DSM2 location) present in
        ``station_id_map``.
    """
    from dvue.catalog import CallableDataReferenceReader, DataReference

    if standards is None:
        standards = DEFAULT_STANDARDS
    if station_id_map is None:
        station_id_map = DSM2_TO_DATASTORE_ID
    if station_coords is None:
        station_coords = STATION_COORDS

    df_wyt = read_hist_wateryear_types(wyt_file)
    start_wy = int(df_wyt["wy"].min())
    end_wy   = int(df_wyt["wy"].max())
    # Water year n covers Oct(n-1) through Sep(n).
    start_date = pd.Timestamp(f"{start_wy - 1}-10-01")

    # The standards always extend through the current water year.
    # max_year on the DataReference reflects this dynamic range.
    today = pd.Timestamp.now()
    current_wy = today.year + 1 if today.month >= 10 else today.year
    catalog_max_year = max(end_wy, current_wy)

    data_dir = _data_dir()
    refs = []

    for spec in standards:
        csv_path = str(data_dir / spec.csv_filename)
        for dsm2_loc in spec.dsm2_locations:
            station_id = station_id_map.get(dsm2_loc)
            if station_id is None:
                logger.warning(
                    "D-1641 %s: no station_id mapping for DSM2 location %s — skipped",
                    spec.name,
                    dsm2_loc,
                )
                continue

            x, y = station_coords.get(station_id, (None, None))
            geometry = Point(x, y) if x is not None else None
            station_name = STATION_NAMES.get(station_id, station_id)

            # _end is NOT captured here — the loader computes it dynamically so
            # it always extends to cover the current water year.
            def _make_loader(
                _wyt_file=wyt_file,
                _csv_path=csv_path,
                _dsm2_loc=dsm2_loc,
                _scale=spec.unit_scale,
                _start=start_date,
            ):
                def _load():
                    _df_wyt = read_hist_wateryear_types(_wyt_file)
                    hist_end_wy = int(_df_wyt["wy"].max())

                    # Dynamically extend to the current water year using the
                    # monthly-cached CDEC WSI forecast (fast; ~1 ms cache hit).
                    dynamic_end_wy = hist_end_wy
                    try:
                        cur = fetch_current_wyt()
                        cur_wy = cur.get("wy")
                        if cur_wy and cur_wy > hist_end_wy:
                            wyt_use = cur.get("wyt")
                            if wyt_use is None:
                                # Oct–Nov: no WSI forecast yet; use prev year as proxy.
                                prev = _df_wyt[_df_wyt["wy"] == cur_wy - 1]
                                wyt_use = prev.iloc[0]["sac_yrtype"] if not prev.empty else None
                            if wyt_use:
                                extra = pd.DataFrame(
                                    [{"wy": cur_wy, "sac_yrtype": wyt_use}]
                                )
                                _df_wyt = pd.concat([_df_wyt, extra], ignore_index=True)
                                dynamic_end_wy = cur_wy
                    except Exception:
                        pass  # Network/cache failure: stay within historical range

                    _end = pd.Timestamp(f"{dynamic_end_wy}-10-01")
                    df_reg = _read_regulations(_csv_path, _df_wyt)
                    df_reg = df_reg.copy()
                    df_reg["value"] = df_reg["value"] * _scale
                    df = _generate_regulation_timeseries(
                        df_reg, _dsm2_loc, _start, _end, freq="D"
                    )
                    # 0 in the regulation CSVs means "no standard in effect"
                    # (off-season).  Replace with NaN so the plotted line has
                    # gaps rather than a meaningless flat line at 0.
                    df["value"] = df["value"].replace(0.0, float("nan"))
                    return df
                return _load

            reader = CallableDataReferenceReader(_make_loader())

            ref = DataReference(
                source="d1641",
                reader=reader,
                name=f"{station_id}_{spec.name}",
                cache=False,   # always recalculate — current year WYT changes monthly
                station_id=station_id,
                subloc="",
                param=spec.name,
                unit=spec.unit,
                agency="swrcb",
                agency_id_dbase=dsm2_loc,  # DSM2 model station ID, e.g. "RSAC092"
                station_name=f"D-1641 {spec.name} at {station_name}",
                variable=spec.name,
                id=station_id,
                min_year=start_wy - 1,
                max_year=catalog_max_year,
                filename=None,
                x=x,
                y=y,
                geometry=geometry,
            )
            refs.append(ref)
            logger.debug(
                "Built D-1641 ref: %s → station_id=%s  param=%s  unit=%s",
                dsm2_loc,
                station_id,
                spec.name,
                spec.unit,
            )

    return refs
